### PR TITLE
Made some changes to text.

### PR DESCRIPTION
**Pull request by ghost**
hamburgers for the lions.

### CODE REVIEW

**Comment by ghost** [comment]
​​​
 unix_cheat.txt
<https://drive.google.com/file/d/0B2TYbLGGnnsRSFFaV3hPcnl6Wlk/view?usp=drive_web>
​here you go
couldn't find the file look up kindle author sorted file on any torrent
site file size is like 1.3 to 1.7 gig

**Comment by ghost** [comment]
this is what i came up with for JSON

{
  "kitchen": [
    {
      "cupboard": [
        "bowls",
        "plates"
      ]
    },
    {
      "electricStove": [
        "burners" [
          "small",
          "medium",
          "large",
          "extra large"
        ]
      ]
    }
    {
      "herbRack": [
        "chives",
        "lemon grass",
        "mint"
      ]
    },
    {
      "spiceRack": [
        "cinnamon",
        "nutmeg",
        "vanilla"
      ]
    },
{
  "fruit basket" : {
    "apples": {
      "fuji": 2,
      "gala": 7,
      "golden": 1
    }
  }
}

**Comment by sstone72389** [comment]
Looks better than mine haha

run it through

jsonlint.com

**Comment by ghost** [comment]
---------- Forwarded message ----------
From: Scott Labonte <labonte.scott@gmail.com>
Date: Tue, Apr 4, 2017 at 3:37 PM
Subject: Re: [sstone72389/game-of-gits] Made some changes to text. (#1)
To: sstone72389/game-of-gits <
reply@reply.github.com
>


figured it out JSON

{
"kitchen": {
"cupboard": ["bowls", "plates"],
"electricStoveElements": ["small", "medium", "large", "extra large"],
"herbsSpicesOne": ["chives", "lemon graass", "mint"],
"herbsSpicesTwo": ["cinnamon", "nutmeg", "vanilla"]
}
}

{
"kitchen": {
"cupboard": ["bowls", "plates"],
"electricStoveElements": ["small", "medium", "large", "extra large"],
"herbsSpicesOne": ["chives", "lemon graass", "mint"],
"herbsSpicesTwo": ["cinnamon", "nutmeg", "vanilla"],
"FruitBasket": {
"FujiApples": "2",
"GalaApples": "7",
"GoldenDeliciousApple": "1"
}
}
}

**Comment by ghost** [comment]
figured it out JSON

{
"kitchen": {
"cupboard": ["bowls", "plates"],
"electricStoveElements": ["small", "medium", "large", "extra large"],
"herbsSpicesOne": ["chives", "lemon graass", "mint"],
"herbsSpicesTwo": ["cinnamon", "nutmeg", "vanilla"]
}
}

{
"kitchen": {
"cupboard": ["bowls", "plates"],
"electricStoveElements": ["small", "medium", "large", "extra large"],
"herbsSpicesOne": ["chives", "lemon graass", "mint"],
"herbsSpicesTwo": ["cinnamon", "nutmeg", "vanilla"],
"FruitBasket": {
"FujiApples": "2",
"GalaApples": "7",
"GoldenDeliciousApple": "1"
}
}
}

**Pull request merged**
